version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: task_manager
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Orhun8722
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: task_manager_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: Orhun8722
      MYSQL_DATABASE: task_manager
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306

volumes:
  mysql_data:
